(7926, 4)
hatespeech                    0
counterspeech                 0
predicted_counterspeech    1400
uuid                          0
dtype: int64
Starting Run
Getting Predictions: 0it [00:00, ?it/s]Getting Predictions: 0it [00:04, ?it/s]
Traceback (most recent call last):
  File "/home/amey/depository/cs-eval/gpt-4_inference.py", line 72, in <module>
    content = openai_response(prompt, system_description)
  File "/home/amey/depository/cs-eval/gpt-4_inference.py", line 45, in openai_response
    response = client.chat.completions.create(
  File "/home/amey/miniconda3/envs/cs-eval/lib/python3.9/site-packages/openai/_utils/_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
  File "/home/amey/miniconda3/envs/cs-eval/lib/python3.9/site-packages/openai/resources/chat/completions.py", line 590, in create
    return self._post(
  File "/home/amey/miniconda3/envs/cs-eval/lib/python3.9/site-packages/openai/_base_client.py", line 1240, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/amey/miniconda3/envs/cs-eval/lib/python3.9/site-packages/openai/_base_client.py", line 921, in request
    return self._request(
  File "/home/amey/miniconda3/envs/cs-eval/lib/python3.9/site-packages/openai/_base_client.py", line 1005, in _request
    return self._retry_request(
  File "/home/amey/miniconda3/envs/cs-eval/lib/python3.9/site-packages/openai/_base_client.py", line 1053, in _retry_request
    return self._request(
  File "/home/amey/miniconda3/envs/cs-eval/lib/python3.9/site-packages/openai/_base_client.py", line 1005, in _request
    return self._retry_request(
  File "/home/amey/miniconda3/envs/cs-eval/lib/python3.9/site-packages/openai/_base_client.py", line 1053, in _retry_request
    return self._request(
  File "/home/amey/miniconda3/envs/cs-eval/lib/python3.9/site-packages/openai/_base_client.py", line 1020, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
